import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const packageJson = JSON.parse(await readFile(join(root, 'package.json'), 'utf8'));
if (typeof packageJson.version !== 'string' || !/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/.test(packageJson.version)) {
  throw new Error('package.json must contain a valid semver version');
}
const target = join(root, 'src', 'generated-version.ts');
const content = `// This file is generated by scripts/write-version.mjs before every build.\nexport const CHANGEGUARD_VERSION = ${JSON.stringify(packageJson.version)};\n`;
await writeFile(target, content, 'utf8');
